### ISSUE TITLE
Ruby error when running many doc commands

### ISSUE THREAD

**Issue by mklatsky** [nathansamson/docl#2]
I have just installed docl on my Mac Air, running OS X 10.10.1 (Yosemite). I am running ruby 2.0.0p48.

When I initially installed docl, and ran 'docl authorize' I was able to complete that command successful. Also, 'docl help' works.

But other commands do not:

 $ docl keys
/Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/lib/docl/cli.rb:47:in `keys': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/bin/docl:5:in `<top (required)>'
	from /usr/bin/docl:23:in `load'
	from /usr/bin/docl:23:in `<main>'

$ docl regions
/Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/lib/docl/cli.rb:59:in `regions': private method `select' called for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/bin/docl:5:in `<top (required)>'
	from /usr/bin/docl:23:in `load'
	from /usr/bin/docl:23:in `<main>'

Please advise.
Thank you.

**Comment by mboersma** [comment]
I am having a very similar problem:
```console
$ docl regions
/Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/lib/docl/cli.rb:59:in `regions': private method `select' called for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/bin/docl:5:in `<top (required)>'
	from /usr/bin/docl:23:in `load'
	from /usr/bin/docl:23:in `<main>'
```

I'm grasping at straws, trying to install different versions of Ruby to see if one works.

**Comment by mboersma** [comment]
@nathansamson I've had the same results with Ruby versions from 1.9.3 to 2.2.2. Any idea how we can fix this? I'd rather not go back to `tugboat` for Deis DO provisioning.

**Comment by nathansamson** [comment]
I can reproduce this when using an invalid token.
When using a correct token, docl regions & other commands just seem to work (windows 2.2.2)

So I assume the error response for "invalid token" could be very much improved, but besides that things seem to be working....

**Comment by nathansamson** [comment]
I've just comitted v0.0.5 to give errors (from the API) on any failure.

Closing this problem as 0;0.5 should solve the problem
